OperatingSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from processes.views import ProcessViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'processes', ProcessViewSet)


urlpatterns = [
    path('api/',include(router.urls)),
    path('admin/', admin.site.urls, name='admin'),
    path('', TemplateView.as_view(template_name='home/index.html')),
    path('process-management/', include("processes.urls"))
    # path('memoryManagement/',views.memoryManagement,name="memoryManagement"),
    # path('memoryManagement/paging/',views.noofpages,name="paging"),
    # path('memoryManagement/lru/',views.lru_page_replacement,name="lru"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
# urlpatterns = [
#     path("", views.IndexView.as_view(), name="home"),
# ]

processes/urls.py
from django.urls import path
from processes import views


app_name = 'processes'

urlpatterns = [
    path('',views.processManagement,name="all"),
    path('processSchedualing/',views.processSchedualing,name="processSchedualing"),
    path('processSchedualing/fcfs/',views.fcfs,name="fcfs"),
    path('processSchedualing/priority/',views.priority,name="priority"),
    path('create/', views.ProcessCreate.as_view(), name='process_create'),
    path('<int:pk>/delete/', views.ProcessDelete.as_view(), name="process_delete")
]

home/models.py
from django.db import models

# Create your models here.

home/views.py
from django.shortcuts import render

home/templates/home/index.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center bg-dark text-light py-3">YZ Operating System</h1>

<div class="container text-center bg-light">
    <!-- <div class="row justify-content-center"> -->
    <div class="d-grid gap-2 col-5 mx-auto py-2">
        <a class="btn btn-lg btn-primary rounded-0" href="{% url 'processes:all' %}">Process Management</a>
        {% comment %} <a class="btn btn-lg btn-primary rounded-0" href="{% url 'memoryManagement' %}">Memory Management</a> {% endcomment %}
        <!-- <a class="btn btn-lg btn-primary rounded-0" href="">I/O Management</a> -->
    </div>
</div>
{% endblock content %}