OperatingSystem/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import TemplateView
from processes.views import ProcessViewSet
from rest_framework import routers

router = routers.DefaultRouter()
router.register(r'processes', ProcessViewSet)


urlpatterns = [
    path('api/',include(router.urls)),
    path('admin/', admin.site.urls, name='admin'),
    path('', TemplateView.as_view(template_name='home/index.html')),
    path('process-management/', include("processes.urls"))
    # path('memoryManagement/',views.memoryManagement,name="memoryManagement"),
    # path('memoryManagement/paging/',views.noofpages,name="paging"),
    # path('memoryManagement/lru/',views.lru_page_replacement,name="lru"),
]

home/urls.py
from django.urls import path

from . import views

app_name = "home"
# urlpatterns = [
#     path("", views.IndexView.as_view(), name="home"),
# ]

processes/urls.py
from django.urls import path
from processes import views


app_name = 'processes'

urlpatterns = [
    path('',views.processManagement,name="all"),
    path('processSchedualing/',views.processSchedualing,name="processSchedualing"),
    path('processSchedualing/fcfs/',views.fcfs,name="fcfs"),
    path('processSchedualing/priority/',views.priority,name="priority"),
    path('create/', views.ProcessCreate.as_view(), name='process_create'),
    path('<int:pk>/delete/', views.ProcessDelete.as_view(), name="process_delete")
]

processes/models.py
from django.core.validators import MinValueValidator, MaxValueValidator, RegexValidator
from django.db import models

input_regex = RegexValidator(
    regex=r'^P[0-9]{2}$',
    message="Input must start with 'P' followed by two integers letters."
)

# Create your models here.
class processes(models.Model):
    p_id = models.AutoField(primary_key=True)
    process_id = models.CharField(max_length=3, unique=True,validators=[input_regex])
    arrival_time = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    burst_time = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])
    priority = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(10)])
    memory = models.IntegerField(validators=[MinValueValidator(0), MaxValueValidator(100)])

processes/forms.py
from django.forms import ModelForm
from processes.models import processes


# Create the form class.
class ProcessForm(ModelForm):
    class Meta:
        model = processes
        fields = '__all__'

processes/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render, redirect, get_object_or_404
from processes.models import processes
from django.views import View
from django.urls import reverse_lazy
from processes.forms import ProcessForm
from rest_framework import viewsets
from processes.serializers import ProcessSerializer

class ProcessViewSet(viewsets.ModelViewSet):
    queryset = processes.objects.all()
    serializer_class = ProcessSerializer

class ProcessCreate(LoginRequiredMixin, View):
    template = 'processes/process_form.html'
    success_url = reverse_lazy("processes:all")

    def get(self, request):
        form = ProcessForm()
        ctx = {'form': form}
        return render(request, self.template, ctx)

    def post(self, request):
        form = ProcessForm(request.POST)
        if not form.is_valid():
            ctx = {'form': form}
            return render(request, self.template, ctx)
        form.save()
        form.clean
        return redirect(self.success_url)
    
class ProcessDelete(LoginRequiredMixin, View):
    model = processes
    success_url = reverse_lazy('processes:all')
    template = 'processes/process_confirm_delete.html'

    def get(self, request, pk):
        process = get_object_or_404(self.model, pk=pk)
        ctx = {'process': process}
        return render(request, self.template, ctx)

    def post(self, request, pk):
        process = get_object_or_404(self.model, pk=pk)
        process.delete()
        return redirect(self.success_url)


def processSchedualing(request):
    data = {
        "title":"Dispatch Process",
    }
    return render(request, "processes/dispatchProcess.html",data)

def processManagement(request):
    process_table = processes.objects.all()
    data = {
        "title":"Process Management",
        "process_table":process_table
    }
    return render(request, "processes/processManagement.html",data)


def process(request):
    process_table = processes.objects.all()
    data = {
        "title":"Process",
        "process_table":process_table
    }
    return render(request, "processes/process.html",data)

def fcfs(request):
    process_table = processes.objects.all().order_by('arrival_time')
    dictonary = {}
    count = 0
    gantt_chart = []
    for i in process_table:
        gantt_chart.append(count)
        if count < i.arrival_time:
            gantt_chart.append('idle')
            count += i.arrival_time-count
            gantt_chart.append(count)
        gantt_chart.append(i.process_id)
        dictonary[i.process_id] = {}
        dictonary[i.process_id]["PID"] = i.process_id
        dictonary[i.process_id]["Arrival Time"] = i.arrival_time
        dictonary[i.process_id]["Burst Time"] = i.burst_time
        dictonary[i.process_id]["Response Time"] = count - i.arrival_time
        count+=i.burst_time
        dictonary[i.process_id]["Turnaround Time"] = count - i.arrival_time
        dictonary[i.process_id]["Waiting Time"] = dictonary[i.process_id]["Turnaround Time"] - i.burst_time

    gantt_chart.append(count)
    data = {
        "title":"Process Management",
        "schedualing":"First Come First Serve(FCFS)",
        "process_table":dictonary,
        "gantt_chart":gantt_chart,
        # "process_states":process_states,
        "counter":range(count),
    }

    return render(request, "processes/schedualing.html", data)

def priority(request):
    process_table = processes.objects.all().order_by('priority')
    count = 0
    process = list()
    pcb = list()

    for i in process_table:
        process.append(i)

    while process:
        flag = True
        for i in process:
            if i.arrival_time <= count:
                pcb.append(i)
                process.remove(i)
                flag = False
                count+=i.burst_time
                break
        if flag:
            count+=1

    dictonary = {}
    count = 0
    gantt_chart = []
    for i in pcb:
        gantt_chart.append(count)
        if count < i.arrival_time:
            gantt_chart.append('idle')
            count += i.arrival_time-count
            gantt_chart.append(count)
        gantt_chart.append(i.process_id)
        dictonary[i.process_id] = {}
        dictonary[i.process_id]["PID"] = i.process_id
        dictonary[i.process_id]["Priority"] = i.priority
        dictonary[i.process_id]["Arrival Time"] = i.arrival_time
        dictonary[i.process_id]["Burst Time"] = i.burst_time
        dictonary[i.process_id]["Response Time"] = count - i.arrival_time
        count+=i.burst_time
        dictonary[i.process_id]["Turnaround Time"] = count - i.arrival_time
        dictonary[i.process_id]["Waiting Time"] = dictonary[i.process_id]["Turnaround Time"] - i.burst_time
    gantt_chart.append(count)

    data = {
        "title":"Process Management",
        "schedualing":"Priority(Non-Preemptive)",
        "process_table":dictonary,
        "gantt_chart":gantt_chart,
        # "process_states":process_states,
        "counter":range(count),
    }

    return render(request, "processes/schedualing.html", data)

processes/templates/processes/dispatchProcess.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center bg-dark text-light py-3">{{title}}</h1>

<div class="container text-center bg-light">
    <div class="d-grid gap-2 col-5 mx-auto py-2">
        <a class="btn btn-lg btn-primary rounded-0" href="{% url 'processes:fcfs' %}">FCFS</a>
        <a class="btn btn-lg btn-primary rounded-0" href="{% url 'processes:priority' %}">PRIORITY</a>
    </div>
</div>
{% endblock content %}

processes/templates/processes/process.html
{% extends "base.html" %}
{% block content %}

<h1 class="text-center bg-dark text-light py-3">Process Management</h1>

<h2 class="text-center bg-primary text-light my-0 py-2">Process Table</h2>
<table class='table border border-dark'>
    <thead class="bg-dark text-light">
        <th scope='col'>Process ID</th>
        <th scope='col'>Arrival Time</th>
        <th scope='col'>Burst Time</th>
        <th scope='col'>Priority</th>
    </thead>
    <tbody>
        {%for x in process_table%}
        <tr>
            <td>{{x.process_id}}</td>
            <td>{{x.arrival_time}}</td>
            <td>{{x.burst_time}}</td>
            <td>{{x.priority}}</td>
        </tr>
        {% endfor %}
    </tbody>
</table>
{% endblock content %}

processes/templates/processes/processManagement.html
{% extends 'base.html' %}
{% block content %}

<h1 class="text-center bg-dark text-light py-3">{{title}}</h1>

<div class="container text-center bg-light">

<h2 class="text-center bg-dark text-light my-0 py-2">Process Table</h2>
<table class='table border border-dark'>
    <thead class="bg-dark text-light">
        <th scope='col'>Process ID</th>
        <th scope='col'>Arrival Time</th>
        <th scope='col'>Burst Time</th>
        <th scope='col'>Priority</th>
        <th scope='col'>Update</th>
        <th scope='col'>Delete</th>
    </thead>
    <tbody>
        {%for x in process_table%}
        <tr>
            <td>{{x.process_id}}</td>
            <td>{{x.arrival_time}}</td>
            <td>{{x.burst_time}}</td>
            <td>{{x.priority}}</td>
            <td><button type="button" class="btn btn-success">Edit</button></td>
            <td><button type="button" class="btn btn-danger"><a href="{% url 'processes:process_delete' x.id %}">Delete</a></button></td>
        </tr>
        {% endfor %}
    </tbody>
</table>

    <!-- <div class="row justify-content-center"> -->
    <div class="d-grid gap-2 col-5 mx-auto py-2">
        <a class="btn btn-lg btn-primary rounded-0" href={% url 'processes:process_create' %}>Create Process</a>
        <a class="btn btn-lg btn-primary rounded-0" href="{% url 'processes:processSchedualing' %}">Process Schedualing</a>
    </div>
</div>
{% endblock content %}

processes/templates/processes/process_confirm_delete.html
{% extends 'base.html' %}
{% block content %}

<h1>Delete Breed</h1>

<p>Are you sure you want to delete the process: {{ process }}?</p>

<form action="" method="POST">
  {% csrf_token %}
  <input type="submit" value="Yes, delete.">
  <input type="submit" onclick="window.location='{% url 'processes:all' %}' ; return false;" value="Cancel">
</form>

{% endblock %}

processes/templates/processes/process_form.html
{% extends 'base.html' %}
{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
    <input type="submit" onclick="window.location='{% url 'processes:all' %}' ; return false;" value="Cancel">
  </form>
{% endblock %}

processes/templates/processes/schedualing.html
{% extends "base.html" %}
{% block content %}
<h1 class="text-center bg-dark text-light py-3">{{schedualing}}</h1>

<!-- Process Table -->
<h2 class="text-center bg-dark text-light my-0 py-2">Process Table</h2>
<table class='table border border-dark table-light'>
    <thead>
        <th scope='col'>Process ID</th>
        {%if schedualing == "Priority(Non-Preemptive)"%}
            <th scope='col'>Priority</th>
        {%endif%}
        <th scope='col'>Arrival Time</th>
        <th scope='col'>Burst Time</th>
        <th scope='col'>Response Time</th>
        <th scope='col'>Turnaround Time</th>
        <th scope='col'>Waiting Time</th>
    </thead>
    <tbody class="bg-light">
        {%for key,value in process_table.items%}
        <tr>
            {%for k,v in value.items%}
            <td>{{v}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table>

<!-- Gantt Chart -->
<h2 class="text-center bg-dark text-light my-0 py-2">Gantt Chart</h1>
<p class="text-center bg-light p-3">
{% for element in gantt_chart %}
    {% if element|add:1%}
        <sub>{{element}}</sub>
    {% else %}
        <b>{{element}}</b>
    {% endif %}
{% endfor %}
</p>

<!-- Process States -->
<!-- <h2 class="text-center bg-dark text-light my-0 py-2">Process States</h1>
<table class='table border border-dark'>
    <thead class="bg-dark text-light">
        {%for x in process_states%}
        <th scope='col'>{{x}}</th>
        {%endfor%}
    </thead>
    <tbody>
        {%for i in counter%}
        <tr>
            {%for key,value in process_states.items%}
            <td>{{value.0}}</td>
            {% endfor %}
        </tr>
        {% endfor %}
    </tbody>
</table> -->

{% endblock content %}